#!/bin/bash
# MIG-001 T12 — Register SER10 in cascade-state and switch PRIMARY designation.
#
# Run inside WSL on SER10 as usersstas, after T11 (ssh-distribute) succeeded.
#
# What this does:
#   1. git pull --rebase in cascade-state
#   2. Print a templated nodes.md entry for SER10 (manual paste — not auto-edited)
#   3. Print a templated current.md "Active control points" patch (manual paste)
#   4. Prompt to run the manual edits, then re-invoke yourself to commit.
#
# Why manual: state files contain narrative prose; auto-editing risks corrupting
# structure. The Stanislav/operator step here is small (<5 minutes of editing).
#
# Logs to /tmp/mig-001-11-state-init.log.

set -euo pipefail
LOG=/tmp/mig-001-11-state-init.log
exec > >(tee -a "$LOG") 2>&1
echo "==== $(date -Iseconds) MIG-001 T12 state-init start ===="

cd ~/projects/cascade-state

echo "[1/3] git pull --rebase..."
git pull --rebase

TAILNET_IP=$(tailscale.exe ip -4 2>/dev/null | tr -d '[:space:]' || echo "<unknown — check 'tailscale.exe ip -4'>")
DATE=$(date +%Y-%m-%d)

echo ""
echo "[2/3] Paste this block into state/nodes.md (under the appropriate section):"
echo ""
cat <<EOF
- **ser10-tha-1** (TS $TAILNET_IP)
  - Beelink SER10 MAX, AMD Ryzen AI 9 HX 470 (12C/24T, 5.2 GHz boost)
  - iGPU Radeon 890M (16 CUs, RDNA 3.5, 3100 MHz); NPU XDNA 2 (55 TOPS); 86 TOPS combined
  - 10 GbE LAN, USB4 40 Gbps, HDMI 2.1 + DP 2.1 (triple 4K@240Hz)
  - Storage: STOCK 1TB NVMe (root); WD_BLACK SN7100 4 TB arrives 2026-05-21 (T14)
  - RAM: STOCK 32 GB; Crucial CT2K48G56C46S5 96 GB DDR5-5600 SODIMM kit arrives 2026-05-28 (T15)
  - OS: Win11 + WSL2 Ubuntu-24.04
  - Tailscale account: krom00070007@gmail.com
  - Tailscale SSH: **DISABLED** (org-wide rule)
  - Funnel: https://ser10-tha-1.tail80c5d4.ts.net/ (cascade-browser MCP on :8767)
  - Role: **PRIMARY control point** (since $DATE; MSI demoted to BACKUP)
  - Bearer token storage: ~/.cascade-browser/bearer.txt (chmod 600, generated by 07-cascade-browser-setup.sh)
  - SSH key: cowork-ser10-tha-1-wsl2-$(date +%Y%m%d) (ed25519); distributed to 6 nodes in T11
EOF

echo ""
echo "[3/3] Patch state/current.md \"Active control points\" section:"
echo ""
cat <<EOF
Replace the existing block with:

- **SER10 Pattaya-1** (ser10-tha-1, TS $TAILNET_IP, Win11 + WSL2 Ubuntu-24.04, \`usersstas\`)
  — **PRIMARY** as of $DATE. Beelink SER10 MAX, stock 32 GB + 1 TB pending
  RAM swap 2026-05-28 (→ 96 GB) and NVMe expansion 2026-05-21 (→ +4 TB on M.2 slot 2).
- **MSI** (DESKTOP-4SL95N4, TS 100.117.0.35, WSL2 Ubuntu-24.04, \`usersstas\`)
  — **BACKUP** as of $DATE. Claude Code 2.1.138 PINNED (2.1.139 incident, R-141..R-147).
EOF

echo ""
echo "==== T12 — manual edits expected ===="
echo "Open these in your editor:"
echo "  ~/projects/cascade-state/state/nodes.md"
echo "  ~/projects/cascade-state/state/current.md"
echo ""
echo "After edits, run T18 (the final commit step):"
echo "  cd ~/projects/cascade-state"
echo "  git add state/nodes.md state/current.md"
echo "  git commit -m 'MIG-001: SER10 Pattaya-1 PRIMARY (BACKUP→MSI)'"
echo "  git push origin main"
echo "  # post-commit hook auto-pushes the state mirror to opus"
