#!/bin/bash
# 05-sysctl-tuning — performance + exit-node networking
#
# Goals:
#  - Minimal latency / max throughput для exit-node forwarding
#  - TCP BBR (better than CUBIC для high-bandwidth, long-latency paths)
#  - Large socket buffers
#  - IP forwarding (mandatory для exit-node!)
#  - Connection tracking tuned для high-concurrency

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/cascade-server-setup.conf"

SYSCTL_FILE=/etc/sysctl.d/99-cascade-tuning.conf

cat > "$SYSCTL_FILE" <<'EOF'
# ===== Cascade server tuning =====
# Generated by cascade-server-setup.

# ----- IP forwarding (CRITICAL для exit-node) -----
net.ipv4.ip_forward = 1
net.ipv6.conf.all.forwarding = 1

# ----- TCP congestion control: BBR (Google) -----
# Better than CUBIC для VPN / chained-routing on high-latency links
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# ----- TCP Fast Open -----
# Reduces handshake latency (3 = enabled for client and server)
net.ipv4.tcp_fastopen = 3

# ----- Socket buffers (для high-bandwidth) -----
# Default читаемые/писательские буферы — Linux обычно 208 KB, увеличиваем до 8 MB
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216

# TCP-specific
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216

# ----- TCP behavior -----
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_sack = 1
net.ipv4.tcp_fack = 0
net.ipv4.tcp_dsack = 1

# ----- Connection tracking (для много NAT exit-traffic) -----
net.netfilter.nf_conntrack_max = 524288
net.netfilter.nf_conntrack_buckets = 131072
net.netfilter.nf_conntrack_tcp_timeout_established = 7200

# ----- File descriptor limits (для high-concurrency сервера) -----
fs.file-max = 1000000

# ----- Backlog queues -----
net.core.netdev_max_backlog = 16384
net.core.somaxconn = 8192
net.ipv4.tcp_max_syn_backlog = 8192

# ----- ICMP / general -----
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# ----- Disable обычно-not-нужные protocol layers -----
net.ipv4.tcp_max_tw_buckets = 1440000
net.ipv4.tcp_fin_timeout = 15
EOF

# Apply
sysctl -p "$SYSCTL_FILE" >/dev/null 2>&1 || sysctl --system >/dev/null 2>&1 || true

# Verify BBR available
if ! sysctl -n net.ipv4.tcp_available_congestion_control 2>/dev/null | grep -q bbr; then
    echo "WARN: BBR not available — kernel may need newer version. Falling back to default."
    sed -i 's/^net.ipv4.tcp_congestion_control.*/# tcp_congestion_control = bbr (kernel missing bbr)/' "$SYSCTL_FILE"
    sysctl -p "$SYSCTL_FILE" >/dev/null 2>&1 || true
fi

# ulimit для всех users (PAM-based)
cat > /etc/security/limits.d/99-cascade.conf <<EOF
*               soft    nofile          524288
*               hard    nofile          1048576
root            soft    nofile          524288
root            hard    nofile          1048576
EOF

# Verify
echo "[05] sysctl tuning applied:"
echo "  ip_forward: $(sysctl -n net.ipv4.ip_forward)"
echo "  congestion control: $(sysctl -n net.ipv4.tcp_congestion_control)"
echo "  default qdisc: $(sysctl -n net.core.default_qdisc)"
echo "  rmem_max: $(sysctl -n net.core.rmem_max)"
echo "  nf_conntrack_max: $(sysctl -n net.netfilter.nf_conntrack_max 2>/dev/null || echo n/a)"
